### ISSUE TITLE
Grads mismatch when running tests

### ISSUE THREAD

**Issue by ni1lloc** [HawkAaron/warp-transducer#16]
Hello,
Which version of GPU driver&CUDA library are you working on?
The test cases fail on a Tesla K80 GPU, with 375.26 driver, CentOS 7. 
It's confusing me that I'm getting different results with different CUDA versions, and no other errors happened.

CUDA 8.0/cuDNN7.1.3
![image](https://user-images.githubusercontent.com/17943172/56469219-31b80d00-6469-11e9-9ba3-0ab4fed0c8a0.png)

CUDA 7.5/cuDNN5.1
![image](https://user-images.githubusercontent.com/17943172/56469286-64163a00-646a-11e9-8b9b-4ba82457f3c7.png)

CUDA 7.5/cuDNN6.0
![image](https://user-images.githubusercontent.com/17943172/56469320-0df5c680-646b-11e9-9652-0927d23695d5.png)

**Comment by HawkAaron** [comment]
Hi, I'm working on CUDA 9.0, CUDA driver 390.67 and GPU Tesla K40m / GeForce GTX 1080 Ti.
Since this library doesn't rely on cuDNN, there is no need to enumerate on cuDNN versions.

**Comment by ni1lloc** [comment]
Thanks for your reply. Now it works fine on CUDA 9.0/driver 390.30
